### ISSUE TITLE
Peaks List Items

### ISSUE THREAD

**Issue by mountaingoat69** [WebCab-Design/peaksrecovery.com#2]
Header section: Let's get to work on moving header/ slider section in direction of Betty Ford website like we talked about @TheBurnsby 

Header images throughout pages within site: Please just set those up and I will go back through with appropriate pictures. 

Photos of homes and office: I'll compile those and get into GitHub

Staff section: Transfer all photos over form current peaksrecovery.com site 

Left Sidebar on any page, let's move to right side bar. 

Addiction treatment pages and Mental Health pages, let's add brochure to each of those sections as well. Can we add brochure link to footer section? Let me know. 

Make sure all pages are linked accordingly: I've put most of the content up for the site right now. Just need to put together content for a few pages under mental health tab. 

That's it for now... @TheBurnsby

**Comment by TheBurnsby** [comment]
Still working on the Office photos and staff sections!
